# Generated by Django 5.1.5 on 2025-04-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution_craft_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Open', max_length=50),
        ),
    ]
